version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    command: ["--bind_ip", "0.0.0.0"]
  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_USERNAME=rootuser
      - MONGO_PASSWORD=rootpass
      - MONGO_DATABASE=tweetsdb
    depends_on:
      - mongodb
volumes:
  data: {}

networks:
  default:
    name: mongo_network
