version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    command: ["--bind_ip", "0.0.0.0"]
  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_USERNAME=rootuser
      - MONGO_PASSWORD=rootpass
      - MONGO_DATABASE=tweetsdb
    depends_on:
      - mongodb
#   app-client:
#     build:
#       context:  ../tweetsreact # Use an image built from the specified dockerfile in the `polling-app-client` directory.
#       dockerfile: Dockerfile
#       args:
#         REACT_APP_API_BASE_URL: http://127.0.0.1:3000
#     ports:
#       - "3000:3000" # Map the exposed port 80 on the container to port 9090 on the host machine
#     restart: always
#     depends_on:
#       - api_service
volumes:
  data: {}

networks:
  default:
    name: mongo_network
