server:
  port: 8080
  servlet:
    context-path: /api/v1.0/tweets

management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: health, shutdown, prometheus
  endpoint:
    shutdown:
      enabled: true

spring:
  session:
    store-type: mongodb
    timeout:
      seconds: 600
  data:
    mongodb:
      authentication-database: admin
      username: ${MONGO_USERNAME:rootuser}
      password: ${MONGO_PASSWORD:rootpass}
      database: ${MONGO_DATABASE:tweetsdb}
      host: ${MONGO_HOST:localhost}
      port: 27017
      auto-index-creation: true

logging:
  file: ./application.log

